stages:
  - check-changelog
  - run-test-suite

check-changelog:
  tags:
    - shell
    - quartz
  stage: check-changelog
  only:
    - merge_requests
  allow_failure: true
  script:
    - echo "===== Begin Changelog Check ====="
    - echo "Merge request diff SHA - $CI_MERGE_REQUEST_DIFF_BASE_SHA"
    - git fetch
    - CHANGES=$(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA...HEAD | grep '^CHANGELOG.md$')
    - if [ -n "$CHANGES" ]; then
        echo "===== Changelog has been updated! =====";
      else
        echo "ERROR Changelog not updated";
        exit 1;
      fi

# trigger_tests:
#   stage: run-test-suite
#   trigger:
#     project: kur1/deepopt_tests

trigger_tests:
  tags:
    - shell
    - quartz
  stage: run-test-suite
  script:
    - curl -X POST --fail -F token=$CI_JOB_TOKEN -F ref=main https://lc.llnl.gov/gitlab/api/v4/projects/7151/trigger/pipeline
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
