stages:
  - check-changelog
  - run-test-suite

variables:
  GIT_DEPTH: 50

check-changelog:
  tags:
    - shell
    - quartz
  stage: check-changelog
  only:
    - merge_requests
  allow_failure: true
  script:
    - echo "===== Begin Changelog Check ====="
    - echo "Commit at HEAD of target branch - $CI_MERGE_REQUEST_DIFF_BASE_SHA"
    - echo "Commit at HEAD of source branch - $CI_COMMIT_SHA"
    - CHANGES=$(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA | grep '^CHANGELOG.md$')
    - if [ -n "$CHANGES" ]; then
        echo "===== Changelog has been updated! =====";
      else
        echo "ERROR Changelog not updated";
        exit 1;
      fi

# trigger_tests:
#   tags:
#     - shell
#     - quartz
#   stage: run-test-suite
#   script:
#     - curl -X POST --fail -F token=glptt-6041feae03d10ca5577bb3d080e9e56897231fc7 -F ref=main https://lc.llnl.gov/gitlab/api/v4/projects/7151/trigger/pipeline
#   rules:
#     - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

.downstream-test-pipeline:
  variables:
    UPSTREAM_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  trigger:
    project: kur1/deepopt_tests
    branch: main
    strategy: depend

run-test-suite:
  stage: run-test-suite
  extends: .downstream-test-pipeline
  environment:
    name: test-suite-run/$CI_COMMIT_REF_SLUG
