stages:
  - check-changelog
  - run-test-suite
  - cleanup

variables:
  GIT_DEPTH: 50

check-changelog:
  tags:
    - shell
    - quartz
  stage: check-changelog
  only:
    - merge_requests
  allow_failure: true
  script:
    - echo "===== Begin Changelog Check ====="
    - echo "Commit at HEAD of target branch - $CI_MERGE_REQUEST_DIFF_BASE_SHA"
    - echo "Commit at HEAD of source branch - $CI_COMMIT_SHA"
    - CHANGES=$(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA | grep '^CHANGELOG.md$')
    - if [ -n "$CHANGES" ]; then
        echo "===== Changelog has been updated! =====";
      else
        echo "ERROR Changelog not updated";
        exit 1;
      fi

.downstream-test-pipeline:
  only:
    - merge_requests
  variables:
    UPSTREAM_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    UPSTREAM_ENVIRONMENT_ACTION: $CI_ENVIRONMENT_ACTION
  trigger:
    project: kur1/deepopt_tests
    branch: main
    strategy: depend

run-test-suite:
  stage: run-test-suite
  extends: .downstream-test-pipeline
  environment:
    name: test-suite/$CI_COMMIT_REF_SLUG
    on_stop: clean-test-suite

clean-test-suite:
  stage: cleanup
  extends: .downstream-test-pipeline
  environment:
    name: test-suite/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual
