variables:
  ALLOC_NAME: "deepopt_gitlab_runner_build_test_alloc_${CI_PIPELINE_ID}"

stages:
  - allocate
  - changelog
  - test-unit
  # - test-integration
  # - deploy
  - deallocate

allocate_nodes:
  tags:
    - shell
    - quartz
  stage: allocate
  script:
    - echo "===== begin alloc for remaining stages ====="
    -  salloc -N 1 --exclusive -p pdebug -t 60 --no-shell --job-name=$ALLOC_NAME
    - JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
    - echo "===== alloc'd JOBID $JOBID ====="

deallocate_nodes:
  tags:
    - shell
    - quartz
  stage: deallocate
  when: always
  script:
    - export JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
    - ([[ -n "${JOBID}" ]] && scancel ${JOBID} || echo "Job ${JOBID} not running")

.changelog:
  tags:
    - shell
    - quartz
  stage: changelog
  script:
    - echo "===== begin changelog ====="
    - pwd

.test-unit:
  tags:
    - shell
  script:
    - echo "===== begin test-unit ====="
    - pwd
    - which python3
    - python3 --version

test-unit-3.8:
  extends: .test-unit
  stage: test-unit
  image: python:3.8

test-unit-3.9:
  extends: .test-unit
  stage: test-unit
  image: python:3.9
