stages:
  - check-changelog
  - run-test-suite

check-changelog:
  tags:
    - shell
  stage: check-changelog
  only:
    - merge_requests
  script:
    - echo "===== Begin Changelog Check ====="
    - echo $CI_COMMIT_BEFORE_SHA
    - echo $CI_COMMIT_SHA
    - grep '^CHANGELOG.md$'
    # - CHANGES=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^CHANGELOG.md$')
    # - if [ -n "$CHANGES" ]; then
    #     echo "===== Changelog has been updated! =====";
    #   else
    #     echo "ERROR Changelog not updated";
    #     exit 1;
    #   fi

# trigger_tests:
#   stage: run-test-suite
#   trigger:
#     project: kur1/deepopt_tests

trigger_tests:
  stage: run-test-suite
  script:
    - curl -X POST -F token=$CI_JOB_TOKEN -F ref=main https://gitlab.com/api/v4/projects/7151/trigger/pipeline
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
