site_name: DeepOpt

nav:
  - DeepOpt: "index.md"
  - User Guide:
    - Overview: "user_guide/index.md"
    - Installation: "user_guide/installation.md"
    - Tutorial: "user_guide/tutorial.md"
    - Configuration: "user_guide/configuration.md"
    - Acquisition Functions: "user_guide/acquisition_functions.md"
  - Reference Guide:
    - DeepOpt Reference: "api_reference/index.md"
    - API Reference: "api_reference/"
  - Contributing: "contributing.md"
  - Contact Us: "contact.md"

theme:
  name: material
  language: en
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: purple
      accent: orange
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: purple
      accent: orange

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - glightbox
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths: [deepopt]
          options:
            docstring_style: sphinx
  - literate-nav:
      nav_file: SUMMARY.md

extra:
  social:
    # - icon: fontawesome/brands/github
    #   link: https://lc.llnl.gov/gitlab/kur1/deepopt_release
    #   name: DeepOpt on GitHub
    - icon: fontawesome/brands/gitlab
      link: https://lc.llnl.gov/gitlab/deepopt-devs/deepopt
      name: DeepOpt on GitLab

extra_css:
  - stylesheets/custom_api_style.css

copyright: Copyright &copy; 2023 | Brian Gunnarson, Eugene Kur, Ryan Tran
